### ISSUE TITLE
Improve project folder structure

### ISSUE THREAD

**Issue by bhattabhi013** [singhrishabh93/Hacktoberfest-2022#23]
What:
A large number of files are lying in the root folder.
I think we should assign the files to their respective folders. ex: all files containing sell in the `Sell` folder.

Screenshot:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/47862474/193420325-3c959e74-7efd-4ea5-8dae-b23db1118d67.png">

**Comment by 1-Sanchit-1** [comment]
I would like to work on this issue! ...

**Comment by singhrishabh93** [comment]
> 



> I would like to work on this issue! ...

@bhattabhi013 Thank You for finding this issue 
You can work on this issue.
I've assigned this to you.

**Comment by omgoyal22** [comment]
hey i would like to work on this I may do it very early! please assign me

**Comment by singhrishabh93** [comment]
> hey i would like to work on this I may do it very early! please assign me

Okay try
