### ISSUE TITLE
Improve some styling in form while selling items.

### ISSUE THREAD

**Issue by kkartik07** [singhrishabh93/Hacktoberfest-2022#31]
Hey! @singhrishabh93
I would like to make some style changes in the 'Add your Complete Address & select Time-Slot' form that comes while selling a item.
I think the 'confirm and submit' <a> tag needs some styling.
Please assign this to me.
Thanks.

**Comment by singhrishabh93** [comment]
> Hey! @singhrishabh93 I would like to make some style changes in the 'Add your Complete Address & select Time-Slot' form that comes while selling a item. I think the 'confirm and submit' tag needs some styling. Please assign this to me. Thanks.

Okay try to change it

**Comment by kkartik07** [comment]
Hi. I have made a PR. Please review it and merge.
Thanks.

**Comment by surajkeshari** [comment]
Can you please assign this to me under Hacktoberfest label
