### ISSUE TITLE
Add a goto:top button

### ISSUE THREAD

**Issue by ola-nishant** [singhrishabh93/Hacktoberfest-2022#32]
The button should match the overall styling of the website and it should also have similar animations, please assign it to me and add the hacktoberfest label

**Comment by singhrishabh93** [comment]
> The button should match the overall styling of the website and it should also have similar animations, please assign it to me and add the hacktoberfest label

Okay

**Comment by singhrishabh93** [comment]
Okay i've assigned it

**Comment by ola-nishant** [comment]
Sorry,but your repo has been excluded
